services:
    polcode_casper.form.type.user:
        class: Polcode\CasperBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: user }
    
    polcode_casper.form.type.event:
        class: Polcode\CasperBundle\Form\Type\EventType
        tags:
            - { name: form.type, alias: event }         
            
