<?php
namespace Polcode\CasperBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    
    public function getEventsUserIsInvitedTo($user)
    {
        $query = $this->getEntityManager()
                ->createQuery(
                        'Select i, e FROM PolcodeCasperBundle:Invitation i
                        JOIN i.event e
                        WHERE i.user = :user'
                )->setParameter('user', $user); 
        
        try {          
            
            return $query->getArrayResult();
            
        } catch (\Doctrine\ORM\NoResultException $ex) {
            
            return null;

        }
                
    }
   
}