polcode_casper:
    resource: "@PolcodeCasperBundle/Resources/config/routing.yml"
    prefix:   /
    
home_page: 
    path:   /
    defaults: { _controller: PolcodeCasperBundle:Default:index }

register_page:
    path:   /register
    defaults: { _controller: PolcodeCasperBundle:User:register }
    
add_event:
    path:   /add
    defaults:   { _controller: PolcodeCasperBundle:Event:addEvent }
    
login_page:
    path:   /login
    defaults: { _controller: PolcodeCasperBundle:User:login }    
    
login_check:
    path: /login_check
    
logout:
    path: /logout

