polcode_casper:
    resource: "@PolcodeCasperBundle/Resources/config/routing.yml"
    prefix:   /
    
home_page: 
    path:   /
    defaults: { _controller: PolcodeCasperBundle:Default:index }

register_page:
    path:   /register
    defaults: { _controller: PolcodeCasperBundle:User:register }
    
add_event:
    path:   /add
    defaults:   { _controller: PolcodeCasperBundle:Event:addEvent }
    
public_events:
    path:   /public
    defaults:   { _controller: PolcodeCasperBundle:Event:showPublicEvents }    
    
single_event:
    path:   /single/{id}
    defaults:   { _controller: PolcodeCasperBundle:Event:showSingleEvent }   
    
my_events:
    path: /events
    defaults:   { _controller: PolcodeCasperBundle:Event:showUserEvents }
    
edit_event:
    path: /edit/{id}
    defaults:   { _controller: PolcodeCasperBundle:Event:editEvent }
    
ajax_remove_event:
    path: /remove/{id}
    defaults:   { _controller: PolcodeCasperBundle:Event:removeEvent }
    
invite_page:
    path: /invite/{id}
    defaults:   { _controller: PolcodeCasperBundle:User:getAllUsers }
    
login_page:
    path:   /login
    defaults: { _controller: PolcodeCasperBundle:User:login }    
    
login_check:
    path: /login_check
    
logout:
    path: /logout

